apiVersion: v1
kind: Service
metadata:
  name: cip-amstradcpc464
spec:
  selector:
    app: amstradcpc464
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 8464
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cip-commodore64
spec:
  selector:
    app: commodore64
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 8064
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cip-squale
spec:
  selector:
    app: squale
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 8007
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cip-amiga
spec:
  selector:
    app: amiga
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 8500
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cip-atarist
spec:
  selector:
    app: atarist
  ports:
  - protocol: TCP
    name: http-public
    port: 80
    targetPort: 9040
  type: ClusterIP